package element.setting;

public enum ElementStatus {
	PRESENT, NOT_PRESENT, 
	DISPLAYED, NOT_DISPLAYED, 
	CLICKABLE, NOT_CLICKABLE, 
	ENABLED, DISABLED, 
	SELECTED, NOT_SELECTED,
	TEXT_TO_BE, TEXT_CHANGED,
	ATTRIBUTE_TO_BE, ATTRIBUTE_CHANGED
}
